name = "Quoll"
uuid = "9d051eb3-b680-40d1-9fd2-1a9acedfca1f"
version = "0.1.0"
authors = ["Valdas Vitartas <valdas.vitartas@warwick.ac.uk> and contributors"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsIOPython = "9e4c859b-2281-48ef-8059-f50fe53c37b0"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
Aqua = "0.8"
ArgCheck = "2"
AtomsBase = "0.5"
AtomsBaseTesting = "0.4"
AtomsIOPython = "0.1"
AutoHashEquals = "2"
AxisKeys = "0.2"
CodecZlib = "0.7"
Configurations = "0.17"
DelimitedFiles = "1.9.1"
Dictionaries = "0.4"
HDF5 = "0.17"
JSON = "1.2.1"
LoggingExtras = "1.1"
MPI = "0.20"
MPIPreferences = "0.1.11"
NeighbourLists = "0.5"
OffsetArrays = "1.17"
Reexport = "1.2"
SafeTestsets = "0.1"
StaticArrays = "1.9"
StructArrays = "0.7"
Unitful = "1.25"
UnitfulAtomic = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
AtomsBaseTesting = "ed7c10db-df7e-4efa-a7be-4f4190f7f227"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "LoggingExtras", "AtomsBaseTesting", "Test", "SafeTestsets", "Tar", "CodecZlib"]
