name = "Quoll"
uuid = "9d051eb3-b680-40d1-9fd2-1a9acedfca1f"
authors = ["Valdas Vitartas <valdas.vitartas@warwick.ac.uk> and contributors"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ArgCheck = "2"
AtomsBase = "0.5"
Configurations = "0.17"
Dictionaries = "0.4"
Reexport = "1.2"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "SafeTestsets"]
